POST    
Content-Type: application/json

{
    
        "firstName":"siddanth",
        "lastName":"",
        "gender":"Male",
        "email":"siddanth@gmail.com",
        "Phno":8967642874,
        "password":"hello2",
        "user_cart":[],
        "user_wishlist":[],
        "recently_viewed":[],
        "address_list":[
            {
                "house_no":0,
                "street":"",
                "landmark":"",
                "city":"Bangalore",
                "state":"Karnataka",
                "country":"India",
                "pincode":32234
            }
        ],
        "orderHistory":[]
    
}