POST http://localhost:3001/user/signIn
Content-Type: application/json

{
    "email":"prashanth@gmail.com",
    "password":"hello world"
}

###
POST  http://localhost:3001/user/forgot-password
Content-Type: application/json

{
    "email":"prashanth@gmail.com"
}